### Get app name

GET http://127.0.0.1:43567/api/v1/backend/app-name

### Refresh network interfaces

POST http://127.0.0.1:43567/api/v1/refresh/netinf

### Start VSC

POST http://127.0.0.1:43567/api/v1/vsc/start

### Stop VSC

POST http://127.0.0.1:43567/api/v1/vsc/stop