app:
  name: AES67-VSC-2 Receiver
  instance:
    name: thinkpad-p14s/2
telemetry:
  endpoint: !grpc http://127.0.0.1:4317
playoutConfig:
  webserver:
    bindAddress: 127.0.0.1
    port: 32003
  receiver: http://127.0.0.1:32002
receiverConfig:
  webserver:
    bindAddress: 127.0.0.1
    port: 32002
  session: |
    v=0
    o=- 123456 123458 IN IP4 10.0.1.2
    s=My sample flow
    i=4 channels: c1, c2, c3, c4
    t=0 0
    a=recvonly
    m=audio 5004 RTP/AVP 98
    c=IN IP4 239.69.11.44/32
    a=rtpmap:98 L24/48000/4
    a=ptime:1
    a=ts-refclk:ptp=IEEE1588-2008:00-11-22-FF-FE-33-44-55:0
    a=mediaclk:direct=0
  linkOffset: 4
  bufferOverhead: 10
  interfaceIp: 192.168.178.39
