app:
  name: AES67-VSC-2 Receiver
  instance:
    name: thinkpad-p14s
webserver:
  bindAddress: 127.0.0.1
  port: 32000
telemetry:
  endpoint: !grpc http://127.0.0.1:4317
receiverConfig:
  session: |
    v=0
    o=- 10943522194 10943522194 IN IP4 192.168.178.97
    s=AVIO-Bluetooth : 2
    i=2 channels: Left, Right
    c=IN IP4 239.69.232.56/32
    t=0 0
    a=keywds:Dante
    a=recvonly
    m=audio 5004 RTP/AVP 97
    a=rtpmap:97 L24/48000/2
    a=ptime:1
    a=ts-refclk:ptp=IEEE1588-2008:00-1D-C1-FF-FE-0E-10-C4:0
    a=mediaclk:direct=0
  linkOffset: 4
  bufferOverhead: 10
  interfaceIp: "192.168.178.39"
